  QA[m
  feat/adicionando-arquivos[m
  feat/componente-card[m
  feat/componente-navbar[m
  feat/conecao-tela-cadastro[m
  feat/criacao-projeto-vite[m
  feat/landing-page[m
  feat/rotas[m
  feat/tela-campanha[m
  feat/tela-campanha-principal[m
  feat/tela-login[m
  feat/teste-rotas[m
  feature/criar-campanha[m
* [32mfeature/tela-cadastro[m
  feature/tela-voluntariado[m
  fix/correcoes[m
  fix/favion-title-index[m
  fix/imagens-externas[m
  fix/imagens-substituidas[m
  fix/link-navbar-login[m
  fix/padding-header[m
  fix/transportar-index[m
  main[m
